# Generated by Django 5.1 on 2024-08-16 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('IdSede', models.AutoField(primary_key=True, serialize=False)),
                ('NomSede', models.CharField(max_length=20)),
                ('CupoMaximo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TtipoTemporada', models.CharField(choices=[('alta', 'Alta'), ('baja', 'Baja')], max_length=6)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('IdHabitacion', models.AutoField(primary_key=True, serialize=False)),
                ('TipoHabitacion', models.CharField(choices=[('estandar', 'Estandar'), ('premium', 'Premium'), ('vip', 'VIP')], max_length=10)),
                ('CupoMax', models.IntegerField()),
                ('Ocupado', models.CharField(choices=[('si', 'SI'), ('no', 'NO')], max_length=3)),
                ('TarifaTAlta', models.CharField(max_length=10)),
                ('TarifaTBaja', models.CharField(max_length=10)),
                ('Sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.sede')),
            ],
        ),
    ]
