# Generated by Django 5.0.6 on 2024-08-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='TarifaTAlta',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='TarifaTBaja',
            field=models.IntegerField(max_length=10),
        ),
    ]
