# Generated by Django 5.1 on 2024-08-16 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaInicio', models.DateField()),
                ('FechaFin', models.DateField()),
                ('NumPersonas', models.IntegerField()),
                ('TarifaTotal', models.IntegerField()),
                ('Habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.habitacion')),
                ('Sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.sede')),
            ],
        ),
    ]
